// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	models "go-musthave-diploma-tpl/internal/accrual/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckOrderExists mocks base method.
func (m *MockRepository) CheckOrderExists(order int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOrderExists", order)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOrderExists indicates an expected call of CheckOrderExists.
func (mr *MockRepositoryMockRecorder) CheckOrderExists(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOrderExists", reflect.TypeOf((*MockRepository)(nil).CheckOrderExists), order)
}

// CreateProductReward mocks base method.
func (m *MockRepository) CreateProductReward(ctx context.Context, match string, reward float64, rewardType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductReward", ctx, match, reward, rewardType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProductReward indicates an expected call of CreateProductReward.
func (mr *MockRepositoryMockRecorder) CreateProductReward(ctx, match, reward, rewardType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductReward", reflect.TypeOf((*MockRepository)(nil).CreateProductReward), ctx, match, reward, rewardType)
}

// GetAccrualInfo mocks base method.
func (m *MockRepository) GetAccrualInfo(order int64) (string, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccrualInfo", order)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccrualInfo indicates an expected call of GetAccrualInfo.
func (mr *MockRepositoryMockRecorder) GetAccrualInfo(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccrualInfo", reflect.TypeOf((*MockRepository)(nil).GetAccrualInfo), order)
}

// GetProductsInfo mocks base method.
func (m *MockRepository) GetProductsInfo() ([]models.ProductReward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsInfo")
	ret0, _ := ret[0].([]models.ProductReward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsInfo indicates an expected call of GetProductsInfo.
func (mr *MockRepositoryMockRecorder) GetProductsInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsInfo", reflect.TypeOf((*MockRepository)(nil).GetProductsInfo))
}

// GetUnprocessedOrders mocks base method.
func (m *MockRepository) GetUnprocessedOrders() ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessedOrders")
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessedOrders indicates an expected call of GetUnprocessedOrders.
func (mr *MockRepositoryMockRecorder) GetUnprocessedOrders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessedOrders", reflect.TypeOf((*MockRepository)(nil).GetUnprocessedOrders))
}

// ParseMatch mocks base method.
func (m *MockRepository) ParseMatch(match string) ([]models.ParseMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseMatch", match)
	ret0, _ := ret[0].([]models.ParseMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseMatch indicates an expected call of ParseMatch.
func (mr *MockRepositoryMockRecorder) ParseMatch(match interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseMatch", reflect.TypeOf((*MockRepository)(nil).ParseMatch), match)
}

// RegisterNewOrder mocks base method.
func (m *MockRepository) RegisterNewOrder(ctx context.Context, order int64, goods []models.Goods, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNewOrder", ctx, order, goods, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterNewOrder indicates an expected call of RegisterNewOrder.
func (mr *MockRepositoryMockRecorder) RegisterNewOrder(ctx, order, goods, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewOrder", reflect.TypeOf((*MockRepository)(nil).RegisterNewOrder), ctx, order, goods, status)
}

// UpdateAccrualInfo mocks base method.
func (m *MockRepository) UpdateAccrualInfo(ctx context.Context, order int64, accrual float64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccrualInfo", ctx, order, accrual, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccrualInfo indicates an expected call of UpdateAccrualInfo.
func (mr *MockRepositoryMockRecorder) UpdateAccrualInfo(ctx, order, accrual, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccrualInfo", reflect.TypeOf((*MockRepository)(nil).UpdateAccrualInfo), ctx, order, accrual, status)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, status string, order int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, status, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, status, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, status, order)
}
