// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	context "context"
	models "go-musthave-diploma-tpl/internal/accrual/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateProductReward mocks base method.
func (m *MockService) CreateProductReward(ctx context.Context, match string, reward float64, rewardType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductReward", ctx, match, reward, rewardType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProductReward indicates an expected call of CreateProductReward.
func (mr *MockServiceMockRecorder) CreateProductReward(ctx, match, reward, rewardType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductReward", reflect.TypeOf((*MockService)(nil).CreateProductReward), ctx, match, reward, rewardType)
}

// GetAccrualInfo mocks base method.
func (m *MockService) GetAccrualInfo(order int64) (string, float64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccrualInfo", order)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetAccrualInfo indicates an expected call of GetAccrualInfo.
func (mr *MockServiceMockRecorder) GetAccrualInfo(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccrualInfo", reflect.TypeOf((*MockService)(nil).GetAccrualInfo), order)
}

// RegisterNewOrder mocks base method.
func (m *MockService) RegisterNewOrder(ctx context.Context, order models.Order) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNewOrder", ctx, order)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterNewOrder indicates an expected call of RegisterNewOrder.
func (mr *MockServiceMockRecorder) RegisterNewOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewOrder", reflect.TypeOf((*MockService)(nil).RegisterNewOrder), ctx, order)
}
