// Code generated by MockGen. DO NOT EDIT.
// Source: E:\go-musthave-group-diploma-tpl\internal\gophermart\service\gofemart.go
// mockgen -source=E:\go-musthave-group-diploma-tpl\internal\gophermart\service\gofemart.go -destination=E:\go-musthave-group-diploma-tpl\internal\gophermart\service\mocks\mock_service.go -package=mocks
// Package mocks is a generated GoMock package.
package mocks

import (
	models "go-musthave-diploma-tpl/internal/gophermart/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGofemartRepo is a mock of GofemartRepo interface.
type MockGofemartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGofemartRepoMockRecorder
}

// MockGofemartRepoMockRecorder is the mock recorder for MockGofemartRepo.
type MockGofemartRepoMockRecorder struct {
	mock *MockGofemartRepo
}

// NewMockGofemartRepo creates a new mock instance.
func NewMockGofemartRepo(ctrl *gomock.Controller) *MockGofemartRepo {
	mock := &MockGofemartRepo{ctrl: ctrl}
	mock.recorder = &MockGofemartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGofemartRepo) EXPECT() *MockGofemartRepoMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockGofemartRepo) CreateOrder(userID int, orderNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", userID, orderNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockGofemartRepoMockRecorder) CreateOrder(userID, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockGofemartRepo)(nil).CreateOrder), userID, orderNumber)
}

// CreateUser mocks base method.
func (m *MockGofemartRepo) CreateUser(login, password string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", login, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGofemartRepoMockRecorder) CreateUser(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGofemartRepo)(nil).CreateUser), login, password)
}

// GetBalance mocks base method.
func (m *MockGofemartRepo) GetBalance(userID int) (models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", userID)
	ret0, _ := ret[0].(models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockGofemartRepoMockRecorder) GetBalance(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockGofemartRepo)(nil).GetBalance), userID)
}

// GetOrders mocks base method.
func (m *MockGofemartRepo) GetOrders(userID int) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", userID)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockGofemartRepoMockRecorder) GetOrders(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockGofemartRepo)(nil).GetOrders), userID)
}

// GetUserByID mocks base method.
func (m *MockGofemartRepo) GetUserByID(id int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockGofemartRepoMockRecorder) GetUserByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockGofemartRepo)(nil).GetUserByID), id)
}

// GetUserByLoginAndPassword mocks base method.
func (m *MockGofemartRepo) GetUserByLoginAndPassword(login, password string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLoginAndPassword", login, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLoginAndPassword indicates an expected call of GetUserByLoginAndPassword.
func (mr *MockGofemartRepoMockRecorder) GetUserByLoginAndPassword(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLoginAndPassword", reflect.TypeOf((*MockGofemartRepo)(nil).GetUserByLoginAndPassword), login, password)
}

// Withdraw mocks base method.
func (m *MockGofemartRepo) Withdraw(userID int, withdraw models.WithdrawBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", userID, withdraw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockGofemartRepoMockRecorder) Withdraw(userID, withdraw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockGofemartRepo)(nil).Withdraw), userID, withdraw)
}

// Withdrawals mocks base method.
func (m *MockGofemartRepo) Withdrawals(userID int) ([]models.WithdrawBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawals", userID)
	ret0, _ := ret[0].([]models.WithdrawBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdrawals indicates an expected call of Withdrawals.
func (mr *MockGofemartRepoMockRecorder) Withdrawals(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawals", reflect.TypeOf((*MockGofemartRepo)(nil).Withdrawals), userID)
}
